# -*- coding: utf-8 -*-
# See LICENSE file for full copyright and licensing details
{
    'name': 'Tijari Backend Theme',
    'category': 'Themes/Backend',
    'version': '16.0.0.5',
    'author': '',
    'website': '',
    'summary': '',
    'description': "",
    'depends': ['web', 'base_setup', 'portal', 'resource'],
    'data': [
        'security/ir.model.access.csv',
        'data/backend_config_data.xml',
        'data/global_level_config.xml',
        'views/manifest.xml',
        'views/pwa_offline.xml',

        'views/backend_configurator_view.xml',
        'views/res_users_view.xml',
        'views/ir_module_view.xml',
        'views/pwa_shortcuts_view.xml',
        'views/res_config_setting.xml',

        'views/menuitems.xml',
        
        'views/backend_configurator_template.xml',
        'views/login_page_style.xml',
        'views/templates_inherit.xml',
        'views/to_do_list_template.xml',
    ],
    # 'demo': [
    #     'data/tijari_default_images.xml',
    # ],
    'assets': {
        'web.assets_backend': [
            # Qweb files
            '/tijari_theme_backend/static/src/xml/web_inherit.xml',
            '/tijari_theme_backend/static/src/xml/menu.xml',
            '/tijari_theme_backend/static/src/xml/bookmark.xml',
            '/tijari_theme_backend/static/src/xml/base.xml',
            '/tijari_theme_backend/static/src/xml/view_button_icons.xml',
            '/tijari_theme_backend/static/src/xml/list_renderer.xml',
            '/tijari_theme_backend/static/src/xml/form_statusbar.xml',
            # '/tijari_theme_backend/static/src/xml/user_menu.xml',
            '/tijari_theme_backend/static/src/js/widgets/tijariDocumentViewer.xml',

            # scss files
            "/tijari_theme_backend/static/src/scss/custom_varibles.scss",
            "/tijari_theme_backend/static/src/scss/font_icons.scss",
            "/tijari_theme_backend/static/src/scss/font-family.scss",

            "/tijari_theme_backend/static/src/scss/modal.scss",
            "/tijari_theme_backend/static/src/scss/search_modal.scss",
            "/tijari_theme_backend/static/src/scss/chat_window.scss",
            "/tijari_theme_backend/static/src/scss/common_view.scss",
            "/tijari_theme_backend/static/src/scss/discuss_style.scss",
            "/tijari_theme_backend/static/src/scss/list_view.scss",
            "/tijari_theme_backend/static/src/scss/kanban_view.scss",

            "/tijari_theme_backend/static/src/scss/form_view.scss",
            "/tijari_theme_backend/static/src/scss/form_chatter.scss",
            "/tijari_theme_backend/static/src/scss/tree_form_split_view.scss",

            "/tijari_theme_backend/static/src/scss/activity_view.scss",
            "/tijari_theme_backend/static/src/scss/pivot_view.scss",
            "/tijari_theme_backend/static/src/scss/graph_view.scss",
            "/tijari_theme_backend/static/src/scss/dashboards.scss",
            "/tijari_theme_backend/static/src/scss/calendear_view.scss",
            "/tijari_theme_backend/static/src/scss/setting_page.scss",
            "/tijari_theme_backend/static/src/scss/tab_styles.scss",
            "/tijari_theme_backend/static/src/scss/popup_styles.scss",
            "/tijari_theme_backend/static/src/scss/checkbox_styles.scss",
            "/tijari_theme_backend/static/src/scss/radio_styles.scss",
            "/tijari_theme_backend/static/src/scss/separator_styles.scss",
            "/tijari_theme_backend/static/src/scss/search_panel.scss",
            "/tijari_theme_backend/static/src/scss/loader.scss",
            "/tijari_theme_backend/static/src/scss/appdrawer.scss",
            "/tijari_theme_backend/static/src/scss/bookmarks.scss",
            "/tijari_theme_backend/static/src/scss/controlpannel.scss",
            "/tijari_theme_backend/static/src/scss/side_menu.scss",
            "/tijari_theme_backend/static/src/scss/responsive.scss",
            "/tijari_theme_backend/static/src/scss/notification.scss",
            "/tijari_theme_backend/static/src/scss/burger_menu.scss",
            "/tijari_theme_backend/static/src/scss/datetime_pickers.scss",
            "/tijari_theme_backend/static/src/js/widgets/tijariDocumentViewer.scss",
            "/tijari_theme_backend/static/src/scss/website_menu.scss",

            "/tijari_theme_backend/static/src/scss/multi_tab.scss",
            "/tijari_theme_backend/static/src/scss/to_do_list.scss",

            # js files
            '/tijari_theme_backend/static/src/js/widgets/tijariDocumentViewer.js',
            "/tijari_theme_backend/static/src/js/color_pallet.js",
            "/tijari_theme_backend/static/src/js/flip_min.js",
            "/tijari_theme_backend/static/src/js/menu.js",
            "/tijari_theme_backend/static/src/js/user_menu.js",
            "/tijari_theme_backend/static/src/js/apps_menu.js",
            "/tijari_theme_backend/static/src/js/SwitchCompanyMenu.js",
            "/tijari_theme_backend/static/src/js/form_view_renderer.js",
            "/tijari_theme_backend/static/src/js/form_controller.js",
            "/tijari_theme_backend/static/src/js/list_view_renderer.js",
            "/tijari_theme_backend/static/src/js/TijariPageTitle.js",
            "/tijari_theme_backend/static/src/js/pwebapp.js",
            "/tijari_theme_backend/static/src/js/iconpack_load.js",
            "/tijari_theme_backend/static/src/js/action_service.js",
            "/tijari_theme_backend/static/src/js/menu_service.js",
            "/tijari_theme_backend/static/src/js/dialog.js",
        ],
        'web.assets_frontend': [
            '/tijari_theme_backend/static/src/scss/loginpage.scss',
        ],
    },
    'sequence': 1,
    'installable': True,
    'application': True,
    'license': 'OPL-1',
}
